### PR TITLE
Added null check since Oomph can not set the properties on repositories

### PR DESCRIPTION
**Pull request by CWolff92**
Fixes issue #25 by checking if property "usePrivateToken". If null: uses else branch.

### CODE REVIEW

**Comment by pweingardt** [comment]
Thanks for your request. If you to make your life easier:

`"true".equals(thing.getProperty("whatever"))` does kind of the same and is easier. That way you don't need a Null-Check.

**Comment by CWolff92** [comment]
Thanks a lot! I will remember that approach. Do you want me to make another pull request for that? When will the change be taken over in the plug-in repository?

**Comment by pweingardt** [comment]
I will try to update the repository in the next few days.

**Comment by CWolff92** [comment]
Thank you, looking forward to it!

**Comment by pweingardt** [comment]
Done just a few minutes ago. Sorry for the delay ;-).

**Pull request merged**
